version: '3.8'

services:
  bugzora:
    build: .
    image: bugzora:latest
    container_name: bugzora-scanner
    volumes:
      - .:/scan-target:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=UTC
    command: ["--help"]
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp 